### ISSUE TITLE
How to Use

### ISSUE THREAD

**Issue by outercloudstudio** [ItsBlackGear/CaveBiomeAPIFabric#9]
How would someone go about being able to learn and use this API?

**Comment by ItsBlackGear** [comment]
https://github.com/ItsBlackGear/CaveBiomeAPI/blob/main/README.mdhttps://github.com/ItsBlackGear/CaveBiomeAPI/blob/main/README.md

here's an example, i'm working on an update for CBA for both forge and fabric so there will be improved explanation

**Comment by outercloudstudio** [comment]
Unfortunately it looks like the repo is private. I get a 404 error when I try the link.
